Repository MAVERICK-VF142/Object_tracking_in_360_video, pull requests merged in 2024-10, with the labels that each got.

#64 Issue open/close message workflow automation🚀
  .github/workflows/issue-open-close.yml
Labels: GSSoC-Ext, Level2, hacktoberfest-accepted

#61 Successfully Updated CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, hacktoberfest, GSSoC-Ext, Level1

#67 PULL REQUEST RAISE WORKFLOW AUTOMATION🚀
  .github/workflows/pr-raise.yml
Labels: GSSoC-Ext, Level2, hacktoberfest-accepted

#68 PULL REQUEST MERGE WORKFLOW AUTOMATION🚀
  .github/workflows/pr-merge.yml
Labels: GSSoC-Ext, Level2, hacktoberfest-accepted

#72 Implement Issue Reminder Workflow🚀
  .github/workflows/issue-reminder.yml
Labels: enhancement, GSSoC-Ext, Level3, hacktoberfest-accepted

#73 PULL REQUEST CHECKER WORKFLOW AUTOMATION 🚀
  .github/workflows/pr-checker.yml
Labels: GSSoC-Ext, Level2, hacktoberfest-accepted

#71 Updated the readme file
  README.md
  assets/GSSoC-Ext.png
  assets/hacktoberfest.png
  assets/image
Labels: documentation, hacktoberfest, GSSoC-Ext, Level1

#80 adding Stargazers and Forkers section to readme.md
  README.md
Labels: hacktoberfest, GSSoC-Ext, Level1

#81 Added back-to-top button in readme
  README.md
Labels: documentation, hacktoberfest, GSSoC-Ext, Level1
